pub const ERROR_CODE_PATTERN_NOT_FOUND: i32 = 1;
pub const ERROR_CODE_UNKNOWN_DIRECTIVE: i32 = 2;
pub const ERROR_CODE_INVALID_INCLUDE_FORMAT: i32 = 3;
pub const ERROR_CODE_DIRECTORY_TRAVERSAL_FAILED: i32 = 4;
