on: [push, pull_request]
name: CI Suite
jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Run Tests"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose

  run_tgstation:
    name: "Parse TGStation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Install"
        run: cargo install --path ./

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "tgstation/tgstation"
          ref: "master"
          path: "tgstation"

      - name: "Run"
        run: lies
        env:
          GAME_DIR: ./tgstation
										DME_FILE: tgstation.dme

		run_paradise:
    name: "Parse Paradise"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: "Install"
        run: cargo install --path ./

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "ParadiseSS13/Paradise"
          ref: "master"
          path: "paradise"

      - name: "Run"
        run: lies
        env:
          GAME_DIR: ./paradise
										DME_FILE: paradise.dme

		clippy:
    name: "Lints"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Rust"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: "Format"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: "Clippy"
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
